### ISSUE TITLE
long read alignment preset

### ISSUE THREAD

**Issue by ekg** [vgteam/vg#2236]
Today @maickrau brought to my attention a major problem with vg when mapping long reads in realistic data. This has led to a revelation about chunked alignment and a new suggested set of parameters to use for long read mapping.

Here are his tests:

```
pbsim --model-qc model_qc_clr --depth 20 1mb1kgp/z.fa
grep '@' sd_0001.fastq | wc -l
# 6641 reads in total

# construct the z.vg graph
vg construct -r 1mb1kgp/z.fa -v 1mb1kgp/z.vcf.gz -m 32 -p >z.vg
vg index -x z.xg -g z.gcsa -p z.vg

# vg maps most of the pbsim'ed reads with identity <60%
vg map -d z -f sd_0001.fastq -j | jq .identity | awk '{if ($1 < 0.6) print;}' | wc -l
# 4905

# and this doesn't get much better when using settings that tended to improve results in >10kb simulated reads
vg map -d z -f sd_0001.fastq --xdrop-alignment -w 2048 -u 1 --max-gap-length 2048 -j | jq .identity | awk '{if ($1 < 0.6) print;}' |  wc -l
# 3380

# but minimap suggests that no reads should have identity <40%
minimap2 -x map-pb 1mb1kgp/z.fa sd_0001.fastq | tr '\t' '\n' | grep 'dv:f:' | 
cut -d ':' -f 3 | awk '{if ($1 > 0.4) print;}' | wc -l
0

# and GraphAligner agrees
GraphAligner -g z.vg -f sd_0001.fastq -a alns_ga.json
jq .identity < alns_ga.json | awk '{if ($1 < 0.6) print;}' | wc -l
34
```

Basically, with default settings a large number of PacBio reads are aligning with abysmal identity, even though they should have a decent alignment with ~85% identity.

My testing on fixed-length reads (>10kb) with 5% SNP error and 10% indel error didn't show this. Mikko's examination suggests that the simulation of long single-molecule reads is more complex than `vg sim` supports, and that the simplistic model there doesn't capture stuff that's important for real mapping. Those simulations had suggested that better performance was correlated with using a bigger alignment chunk size. I now realize that this wasn't exactly the right solution. The problem has to do with how `vg map` is computing long alignments.

In `vg map`, long alignments is partitioned into chunks of a given size (default 256bp) and each is multimapped independently. The final alignment is found as the max sum path through an alignment DAG where each node represents one of the multi-alignments for a given band and each edge represents a possible transition between bands that occur in order in the read, weighted by the estimated graph distance between them times the gap scoring parameters. _For this process to provide the optimal alignment, then the internal bands should be aligned using a global alignment algorithm, but in fact they are being aligned with a local algorithm that tends to introduce softclips._ This is the source of very low alignment identities that @maickrau found when testing vg map on (simulated, but realistic) pacbio data.

Practically, setting a very high full length alignment bonus mitigates this effect. In testing I find this to be the case, and I resolves the issue that Mikko brought to my attention. It also mitigates the need to use a very large chunk size.

This particular command line provides similar performance in terms of the identity metric to GraphAligner. It's about 5x slower though:

```
vg map -d z -f sd_0001.fastq -u 4 -L 63 -w 128 -k 14 -j >sd_0001.fastq.u4L63w128k14.gam.json
jq .identity <sd_0001.fastq.u4L63w128k14.gam.json | awk '{if ($1 < 0.6) print;}' | wc -l
23
jq .identity <sd_0001.fastq.u4L63w128k14.gam.json | sed s/null/0/ | histogram.py
# NumSamples = 6714; Min = 0.11; Max = 0.91
# Mean = 0.838153; Variance = 0.001138; SD = 0.033732; Median 0.842138
# each ∎ represents a count of 64
    0.1116 -     0.1916 [     2]:
    0.1916 -     0.2715 [     1]:
    0.2715 -     0.3515 [     0]:
    0.3515 -     0.4315 [     3]:
    0.4315 -     0.5114 [     3]:
    0.5114 -     0.5914 [    14]:
    0.5914 -     0.6713 [    14]:
    0.6713 -     0.7513 [    81]: ∎
    0.7513 -     0.8313 [  1747]: ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
    0.8313 -     0.9112 [  4849]: ∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
```

The major failure mode seems to be seeding related, and you can push the sensitivity by dropping -k (minimum MEM length) as low as 8 in this setting. Lower than that isn't reasonable, and in any case 8 probably isn't reasonable for any significantly large genome. This is automatically set based on genome size, but that only makes sense for illumina reads, and for long reads I'd suggest using a fixed setting.

I'm making a note of this here because we should set this as a default setting for long reads. Maybe it should go on the wiki.

**Comment by ekg** [comment]
We've had another iteration on some real data that @maickrau subset for chr22. In the real pacbio data, I found that I also needed to adjust the match, mismatch, gap open, and gap extend scores. I used the ones from minimap2 and found that I was able to get similar performance to minimap2 and GraphAligner.

This was the exact setup that I found to work well:

```
vg map -u 2 -L 63 -q 1 -z 2 -o 2 -y 1 -w 128 ...
```

To make it easier for users to find out how to do this, I've pushed changes to the `vg map` interface that let you do `vg map -m long` to specify the long-read model.

Here's the help text:

```
preset:
    -m, --alignment-model STR     use a preset alignment scoring model, either "short" (default) or "long" (for ONT/PacBio)
                                  "long" is equivalent to `-u 2 -L 63 -q 1 -z 2 -o 2 -y 1 -w 128`
```

Are there any suggestions about how to improve this?

Here's the PR: https://github.com/vgteam/vg/pull/2247

**Comment by ocxtal** [comment]
I haven't noticed that the chunked aligner assumed that each alignment was performed global, but now I'm feeling it's reasonable.

It might be confusing for users that the `full-length bonus` parameter is not interpreted as a real full-length bonus but as an internal parameter. It still won't be a problem when we use this parameter via preset, but there might be a case where full-length bonus for the entire stitched alignment matters. An simple example would be breakpoints around SVs, where an excessive full-length bonus causes overstretched alignments. (though I'm not sure yet if it really affects or not...)

If global (or something pinned) alignment API is needed for this purpose, I'm ready to implement it in the dozeu.

Thanks,

**Comment by faithokamoto** [comment]
We now want people to align long reads using `vg giraffe`'s long-read modes (`-b hifi` or `-b r10`), so fixing `vg map` workflows isn't on the docket.
